# Generated by Django 3.0.1 on 2019-12-30 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('released', models.DateTimeField()),
                ('published_year', models.DateField()),
                ('image', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Album names',
            },
        ),
        migrations.CreateModel(
            name='BandMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('profile_pic', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('date_joined', models.DateField()),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Band members',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('added_date', models.DateField(auto_now=True)),
                ('modified_date', models.DateField(blank=True, null=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bands.Album')),
                ('genre', models.ManyToManyField(to='bands.Genre')),
                ('member_name', models.ManyToManyField(to='bands.BandMember')),
            ],
        ),
        migrations.CreateModel(
            name='MusicalBand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=50)),
                ('musical_band_established_date', models.DateField()),
                ('location', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
                ('cover_image', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Musical band',
            },
        ),
        migrations.AddField(
            model_name='bandmember',
            name='role',
            field=models.ManyToManyField(to='bands.Role'),
        ),
        migrations.AddField(
            model_name='album',
            name='music_band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bands.MusicalBand'),
        ),
    ]
